### ISSUE TITLE
Poor translation

### ISSUE THREAD

**Issue by SafaAlfulaij** [javascript-tutorial/ar.javascript.info#158]
I was going through the articles, and... oh my god. The amount of poor translations (almost in every paragraph in every article) is insanly huge.
From language mistakes, to meaning mistakes, to formatting mistakes, to presentation mistakes, it's just a can full of worms.

This “issue” can be classified as “rethink translation”.
I'm ready to point to mistakes in any article you want.

## Solution
I’ll be honest and say, re-translate everything.

**Comment by OmarioHasan** [comment]
Hello @SafaAlfulaij,
Most of the translated articles are taken from `Hasoub Academy` and they have a perfect team in the translation and revision.
So you can make your contribution and fix what you see that it needs to fix
Also, re-translate is not an easy option to get 
Regards
@Jamil-Bailony @3imed-jaberi  @atefBB

**Comment by atefBB** [comment]
<div dir="rtl">شكرا. نرحب بملاحظاتك واسهامك، وحقيقة نحن في أمس الحاجة لذلك. يمكنك أن ترسل لنا ملاحظاتك وسعيد جدا بتفاعلك.</div>
