### ISSUE TITLE
Publishing epub/pdf

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/ar.javascript.info#174]
Hi,

I'd like to try publishing the epub/pdf, could you translate some phrases for that, please?

[ar.yml.zip](https://github.com/javascript-tutorial/ar.javascript.info/files/6120967/ar.yml.zip)

@OmarioHasan

**Comment by OmarioHasan** [comment]
Sure

**Comment by OmarioHasan** [comment]
@iliakan 
[ar.yml.zip](https://github.com/javascript-tutorial/ar.javascript.info/files/6121200/ar.yml.zip)

**Comment by iliakan** [comment]
Is this acceptable?
[js.pdf](https://github.com/javascript-tutorial/ar.javascript.info/files/6122104/js.pdf)

**Comment by OmarioHasan** [comment]
I think you need to use AR font family for arabic sentense
Also, the direction needs to be RTL
We will invest some hard work to review old translation and translate the rest

**Comment by iliakan** [comment]
Thank you, all other translations are LTR, and I really lack the experience with RTL stuff. 

Still, I hope we can make epub/pdf available in Arabic if that's not too difficult.

**Comment by OmarioHasan** [comment]
I'll try to achieve this soon 😊

**Comment by iliakan** [comment]
Here's a piece of the book in HTML. It's then converted to EPUB using Calibre converter.

Does it look good?

If not, what to fix in styles etc?

[work.zip](https://github.com/javascript-tutorial/ar.javascript.info/files/6123373/work.zip)

**Comment by iliakan** [comment]
Moving the discussion to https://github.com/orgs/javascript-tutorial/teams/translate-ar/discussions/3
